HunterTameableDB = {
    ["Bat"] = {
        { name = "Duskbat", zone = "Tirisfal Glades", level = "1–2", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mangy Duskbat", zone = "Tirisfal Glades", level = "3–4", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Greater Duskbat", zone = "Tirisfal Glades", level = "6–7", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Vampiric Duskbat", zone = "Tirisfal Glades", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ressan the Needler", zone = "Tirisfal Glades", level = "11", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Plaguebat", zone = "Eastern Plaguelands", level = "53–55", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 5", "Dive 3" } },
        { name = "Noxious Plaguebat", zone = "Eastern Plaguelands", level = "54–56", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 5" } },
        { name = "Monstrous Plaguebat", zone = "Eastern Plaguelands", level = "56–58", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 6" } }
    },
    ["Fox"] = {
        { name = "Juvenile Vuldren", zone = "Zephras Isle", level = "1", speed = "2.0", rare = false, isNew = true, abilities = {  } },
        { name = "Vuldren", zone = "Zephras Isle", level = "6", speed = "2.0", rare = false, isNew = true, abilities = {  } },
        { name = "Vuldren Alpha", zone = "Zephras Isle", level = "10", speed = "2.0", rare = false, isNew = true, abilities = {  } }
    },
    ["Boar"] = {
        { name = "Mottled Boar", zone = "Durotar", level = "1–2", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Young Thistle Boar", zone = "Teldrassil", level = "1–2", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Thistle Boar", zone = "Teldrassil", level = "2–3", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Battleboar", zone = "Mulgore", level = "3–4", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Small Crag Boar", zone = "Dun Morogh", level = "3", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Bristleback Battleboar", zone = "Mulgore", level = "4–5", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Crag Boar", zone = "Dun Morogh", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Stonetusk Boar", zone = "Elwynn Forest", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Dire Mottled Boar", zone = "Durotar", level = "6–7", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Large Crag Boar", zone = "Dun Morogh", level = "6–7", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Elder Crag Boar", zone = "Dun Morogh", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Porcine Entourage", zone = "Elwynn Forest", level = "7", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Rockhide Boar", zone = "Elwynn Forest", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Elder Mottled Boar", zone = "Durotar", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Princess", zone = "Elwynn Forest", level = "9", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Scarred Crag Boar", zone = "Dun Morogh", level = "9–10", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Corrupted Mottled Boar", zone = "Durotar", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Longsnout", zone = "Elwynn Forest", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Mountain Boar", zone = "Loch Modan", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 1" } },
        { name = "Young Goretusk", zone = "Westfall", level = "12–13", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 2" } },
        { name = "Goretusk", zone = "Westfall", level = "14–15", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 2" } },
        { name = "Mangy Mountain Boar", zone = "Loch Modan", level = "14–15", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 2" } },
        { name = "Elder Mountain Boar", zone = "Loch Modan", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 2" } },
        { name = "Great Goretusk", zone = "Redridge Mountains, Westfall", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 2" } },
        { name = "Bellygrub", zone = "Redridge Mountains", level = "24", speed = "2.0", rare = false, isNew = false, abilities = { "Charge 3" } },
        { name = "Grunter", zone = "Blasted Lands", level = "50", speed = "2.0", rare = true, isNew = false, abilities = { "Dash 3", "Charge 5" } },
        { name = "Plagued Swine", zone = "Riverglades", level = "60", speed = "2.0", rare = true, isNew = true, abilities = {  } }
    },
    ["Tallstrider"] = {
        { name = "Plainstrider", zone = "Mulgore", level = "1–2", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Adult Plainstrider", zone = "Mulgore", level = "6–7", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Plainstrider", zone = "Mulgore, Thunder Bluff", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Ornery Galestrider", zone = "Zephras Isle", level = "8", speed = "1.3", rare = false, isNew = true, abilities = {  } },
        { name = "Mazzranache", zone = "Mulgore", level = "9", speed = "2.0", rare = true, isNew = false, abilities = { "Cower 1" } },
        { name = "Foreststrider Fledgling", zone = "Darkshore", level = "11–13", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Greater Plainstrider", zone = "The Barrens", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Fleeting Plainstrider", zone = "The Barrens", level = "12–13", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Foreststrider", zone = "Darkshore", level = "14–16", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ornery Plainstrider", zone = "The Barrens", level = "16–17", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 2" } },
        { name = "Giant Foreststrider", zone = "Darkshore", level = "17–19", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 2" } },
        { name = "Strider Clutchmother", zone = "Darkshore", level = "20", speed = "2.0", rare = true, isNew = false, abilities = {  } }
    },
    ["Wolf"] = {
        { name = "Ragged Young Wolf", zone = "Dun Morogh", level = "1", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Scavenger", zone = "Tirisfal Glades", level = "1", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Wolf", zone = "Elwynn Forest", level = "1", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ragged Scavenger", zone = "Tirisfal Glades", level = "2–3", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Ragged Timber Wolf", zone = "Dun Morogh", level = "2", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Timber Wolf", zone = "Elwynn Forest", level = "2", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mangy Wolf", zone = "Elwynn Forest", level = "5–6", speed = "1.7", rare = false, isNew = false, abilities = {  } },
        { name = "Prairie Wolf", zone = "Mulgore", level = "5–6", speed = "1.5", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Snow Tracker Wolf", zone = "Dun Morogh", level = "6–7", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Gray Forest Wolf", zone = "Elwynn Forest", level = "7–8", speed = "1.7", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Prairie Stalker", zone = "Mulgore, Thunder Bluff", level = "7–8", speed = "1.5", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Winter Wolf", zone = "Dun Morogh", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Starving Winter Wolf", zone = "Dun Morogh", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Prairie Wolf Alpha", zone = "Mulgore, Thunder Bluff", level = "9–10", speed = "1.4", rare = false, isNew = false, abilities = { "Bite 2", "Furious Howl 1" } },
        { name = "Prowler", zone = "Elwynn Forest", level = "9–10", speed = "1.5", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Coyote", zone = "Westfall", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Timber", zone = "Dun Morogh", level = "10", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 2" } },
        { name = "Worg", zone = "Silverpine Forest, Tirisfal Glades", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2", "Furious Howl 1" } },
        { name = "Coyote Packleader", zone = "Westfall", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2", "Furious Howl 1" } },
        { name = "Mottled Worg", zone = "Silverpine Forest", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Coldrasp", zone = "Tirisfal Glades", level = "12", speed = "1.5", rare = true, isNew = true, abilities = {  } },
        { name = "Gorefang", zone = "Silverpine Forest", level = "13", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Bloodsnout Worg", zone = "Silverpine Forest", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Ghostpaw Runner", zone = "Ashenvale", level = "19–20", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Starving Dire Wolf", zone = "Duskwood", level = "19–20", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Rabid Dire Wolf", zone = "Duskwood", level = "20–21", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mist Howler", zone = "Ashenvale", level = "22", speed = "1.3", rare = true, isNew = false, abilities = { "Furious Howl 1" } },
        { name = "Ghostpaw Howler", zone = "Ashenvale", level = "23–24", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Lupos", zone = "Duskwood", level = "23", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 3" } },
        { name = "Young Black Ravager", zone = "Duskwood", level = "23–24", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Black Ravager", zone = "Duskwood", level = "24–25", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4" } },
        { name = "Black Ravager Mastiff", zone = "Duskwood", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4", "Furious Howl 2" } },
        { name = "Ghostpaw Alpha", zone = "Ashenvale", level = "27–28", speed = "1.3", rare = false, isNew = false, abilities = { "Bite 4", "Furious Howl 2" } },
        { name = "Crag Coyote", zone = "Badlands", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5", "Dash 1" } },
        { name = "Spot", zone = "Dustwallow Marsh", level = "35", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Feral Crag Coyote", zone = "Badlands", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Barnabus", zone = "Badlands", level = "38", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Elder Crag Coyote", zone = "Badlands", level = "39–40", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 1", "Furious Howl 2" } },
        { name = "Longtooth Runner", zone = "Feralas", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6", "Dash 2", "Furious Howl 3" } },
        { name = "Mangy Silvermane", zone = "The Hinterlands", level = "41–42", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Old Cliff Jumper", zone = "The Hinterlands", level = "42", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 6", "Dash 2" } },
        { name = "Rabid Crag Coyote", zone = "Badlands", level = "42–43", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 2" } },
        { name = "Snarler", zone = "Feralas", level = "42", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 6", "Furious Howl 3" } },
        { name = "Longtooth Howler", zone = "Feralas", level = "43–44", speed = "2.0", rare = false, isNew = false, abilities = { "Furious Howl 2" } },
        { name = "Silvermane Wolf", zone = "The Hinterlands", level = "43–44", speed = "2.0", rare = false, isNew = false, abilities = { "Furious Howl 3" } },
        { name = "Silvermane Howler", zone = "The Hinterlands", level = "45–46", speed = "2.0", rare = false, isNew = false, abilities = { "Furious Howl 2" } },
        { name = "Vilebranch Wolf Pup", zone = "The Hinterlands", level = "46–47", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Felpaw Wolf", zone = "Felwood", level = "47–48", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6", "Furious Howl 3" } },
        { name = "Rabid Longtooth", zone = "Feralas", level = "47–48", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Silvermane Stalker", zone = "The Hinterlands", level = "47–48", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 2" } },
        { name = "Death Howl", zone = "Felwood", level = "49", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 6", "Furious Howl 3" } },
        { name = "Felpaw Scavenger", zone = "Felwood", level = "49–50", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Vilebranch Raiding Wolf", zone = "The Hinterlands", level = "50–51", speed = "1.7", rare = false, isNew = false, abilities = { "Bite 7", "Dash 3" } },
        { name = "Ember Worg", zone = "Burning Steppes", level = "51–52", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Felpaw Ravager", zone = "Felwood", level = "51–52", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 7" } },
        { name = "Deathmaw", zone = "Burning Steppes", level = "53", speed = "1.2", rare = true, isNew = false, abilities = {  } },
        { name = "Slavering Ember Worg", zone = "Burning Steppes", level = "53–54", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Blackrock Worg", zone = "Burning Steppes", level = "54–55", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 3" } },
        { name = "Giant Ember Worg", zone = "Burning Steppes", level = "55–56", speed = "2.0", rare = false, isNew = false, abilities = {  } }
    },
    ["Cat"] = {
        { name = "Young Nightsaber", zone = "Teldrassil", level = "1", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mangy Nightsaber", zone = "Teldrassil", level = "2", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mountain Cougar", zone = "Mulgore", level = "3", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Savannah Cub", zone = "The Barrens", level = "4–5", speed = "1.2", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Juvenile Snow Leopard", zone = "Dun Morogh", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Nightsaber", zone = "Teldrassil", level = "5–6", speed = "1.4", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Durotar Tiger", zone = "Durotar", level = "7–8", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Flatland Cougar", zone = "Mulgore, Thunder Bluff", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "Nightsaber Stalker", zone = "Teldrassil", level = "7–8", speed = "1.4", rare = false, isNew = false, abilities = {  } },
        { name = "Snow Leopard", zone = "Dun Morogh", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Nightsaber", zone = "Teldrassil", level = "8–9", speed = "1.4", rare = false, isNew = false, abilities = {  } },
        { name = "Duskstalker", zone = "Teldrassil", level = "9", speed = "1.4", rare = true, isNew = false, abilities = {  } },
        { name = "Flatland Prowler", zone = "Mulgore, Thunder Bluff", level = "9", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Feral Nightsaber", zone = "Teldrassil", level = "10–11", speed = "1.5", rare = false, isNew = false, abilities = {  } },
        { name = "Ghostfang", zone = "Dun Morogh", level = "10", speed = "2.0", rare = true, isNew = true, abilities = {  } },
        { name = "Moonstalker Runt", zone = "Darkshore", level = "10–11", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 1" } },
        { name = "The Rake", zone = "Mulgore", level = "10", speed = "1.2", rare = true, isNew = false, abilities = {  } },
        { name = "Savannah Huntress", zone = "The Barrens", level = "11–12", speed = "1.5", rare = false, isNew = false, abilities = {  } },
        { name = "Savannah Highmane", zone = "The Barrens", level = "12–13", speed = "1.5", rare = false, isNew = false, abilities = {  } },
        { name = "Dishu", zone = "The Barrens", level = "13", speed = "1.5", rare = true, isNew = false, abilities = {  } },
        { name = "Shadowclaw", zone = "Darkshore", level = "13", speed = "1.5", rare = true, isNew = false, abilities = {  } },
        { name = "Moonstalker", zone = "Darkshore", level = "14–15", speed = "1.3", rare = false, isNew = false, abilities = {  } },
        { name = "Savannah Prowler", zone = "The Barrens", level = "14–15", speed = "1.4", rare = false, isNew = false, abilities = {  } },
        { name = "Savannah Patriarch", zone = "The Barrens", level = "15–16", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 2" } },
        { name = "Moonstalker Sire", zone = "Darkshore", level = "17–18", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 2" } },
        { name = "Savannah Matriarch", zone = "The Barrens", level = "17–18", speed = "1.7", rare = false, isNew = false, abilities = {  } },
        { name = "Moonstalker Matriarch", zone = "Darkshore", level = "19–20", speed = "1.3", rare = false, isNew = false, abilities = {  } },
        { name = "Humar the Pridelord", zone = "The Barrens", level = "23", speed = "1.3", rare = true, isNew = false, abilities = {  } },
        { name = "Starving Mountain Lion", zone = "Hillsbrad Foothills", level = "23–24", speed = "1.2", rare = false, isNew = false, abilities = { "Cower 2" } },
        { name = "Twilight Runner", zone = "Stonetalon Mountains", level = "23–24", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 2" } },
        { name = "Crag Stalker", zone = "Thousand Needles", level = "25–26", speed = "1.6", rare = false, isNew = false, abilities = { "Cower 3" } },
        { name = "Feral Mountain Lion", zone = "Hillsbrad Foothills", level = "27–28", speed = "1.2", rare = false, isNew = false, abilities = { "Cower 3" } },
        { name = "Needles Cougar", zone = "Thousand Needles", level = "27–28", speed = "1.2", rare = false, isNew = false, abilities = {  } },
        { name = "Young Panther", zone = "Stranglethorn Vale", level = "30–31", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 3" } },
        { name = "Young Stranglethorn Tiger", zone = "Stranglethorn Vale", level = "30–31", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 3" } },
        { name = "Kurzen War Panther", zone = "Stranglethorn Vale", level = "32–33", speed = "1.3", rare = false, isNew = false, abilities = {  } },
        { name = "Kurzen War Tiger", zone = "Stranglethorn Vale", level = "32–33", speed = "1.3", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Mountain Lion", zone = "Alterac Mountains, Hillsbrad Foothills", level = "32–33", speed = "1.4", rare = false, isNew = false, abilities = { "Prowl 1" } },
        { name = "Hulking Mountain Lion", zone = "Alterac Mountains", level = "33–34", speed = "1.4", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Stranglethorn Tiger", zone = "Stranglethorn Vale", level = "34–35", speed = "1.3", rare = false, isNew = false, abilities = {  } },
        { name = "Araga", zone = "Alterac Mountains", level = "35", speed = "1.4", rare = true, isNew = false, abilities = {  } },
        { name = "Ridge Stalker", zone = "Badlands", level = "36–37", speed = "1.3", rare = false, isNew = false, abilities = { "Cower 4", "Prowl 1" } },
        { name = "Swamp Jaguar", zone = "Swamp of Sorrows", level = "36–37", speed = "1.2", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Broken Tooth", zone = "Badlands", level = "37", speed = "1.0", rare = true, isNew = false, abilities = { "Dash 1" } },
        { name = "Sin'Dall", zone = "Stranglethorn Vale", level = "37", speed = "1.3", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Ridge Huntress", zone = "Badlands", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 4" } },
        { name = "Shadow Panther", zone = "Swamp of Sorrows", level = "39–40", speed = "1.6", rare = false, isNew = false, abilities = { "Prowl 1" } },
        { name = "Bhag'thera", zone = "Stranglethorn Vale", level = "40", speed = "1.5", rare = false, isNew = false, abilities = { "Dash 2" } },
        { name = "Ridge Stalker Patriarch", zone = "Badlands", level = "40–41", speed = "1.3", rare = false, isNew = false, abilities = { "Dash 2", "Prowl 2" } },
        { name = "Elder Shadowmaw Panther", zone = "Stranglethorn Vale", level = "42–43", speed = "1.5", rare = false, isNew = false, abilities = { "Dash 2", "Prowl 2" } },
        { name = "King Bangalash", zone = "Stranglethorn Vale", level = "43", speed = "1.4", rare = false, isNew = false, abilities = { "Dash 2", "Claw 6" } },
        { name = "Jaguero Stalker", zone = "Stranglethorn Vale", level = "50", speed = "2.0", rare = false, isNew = false, abilities = { "Cower 5", "Prowl 3" } },
        { name = "Frostsaber Cub", zone = "Winterspring", level = "55–56", speed = "1.5", rare = false, isNew = false, abilities = { "Cower 6" } },
        { name = "Frostsaber", zone = "Winterspring", level = "56–57", speed = "1.5", rare = false, isNew = false, abilities = {  } },
        { name = "Rak'shiri", zone = "Winterspring", level = "57", speed = "1.5", rare = true, isNew = false, abilities = { "Dash 3" } },
        { name = "Frostsaber Huntress", zone = "Winterspring", level = "58–59", speed = "1.5", rare = false, isNew = false, abilities = { "Dash 3" } },
        { name = "Frostsaber Pride Watcher", zone = "Winterspring", level = "59–60", speed = "1.5", rare = false, isNew = false, abilities = {  } },
        { name = "Frostsaber Stalker", zone = "Winterspring", level = "59–60", speed = "1.5", rare = false, isNew = false, abilities = { "Dash 3", "Prowl 3" } }
    },
    ["Spider"] = {
        { name = "Young Night Web Spider", zone = "Tirisfal Glades", level = "2–3", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Night Web Spider", zone = "Tirisfal Glades", level = "3–4", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Webwood Spider", zone = "Teldrassil", level = "3–4", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Forest Spider", zone = "Elwynn Forest", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Githyiss the Vile", zone = "Teldrassil", level = "5", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Night Web Matriarch", zone = "Tirisfal Glades", level = "5", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Webwood Lurker", zone = "Teldrassil", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Webwood Venomfang", zone = "Teldrassil", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Mine Spider", zone = "Elwynn Forest", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Webwood Silkspinner", zone = "Teldrassil", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Vicious Night Web Spider", zone = "Tirisfal Glades", level = "9–10", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Forest Lurker", zone = "Loch Modan", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Giant Webwood Spider", zone = "Teldrassil", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Mother Fang", zone = "Elwynn Forest", level = "10", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 2" } },
        { name = "Lady Sathrah", zone = "Teldrassil", level = "12", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Moss Stalker", zone = "Silverpine Forest", level = "12–13", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Moss Stalker", zone = "Silverpine Forest", level = "12", speed = "2.0", rare = false, isNew = true, abilities = {  } },
        { name = "Cliff Lurker", zone = "Loch Modan", level = "13–14", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mist Creeper", zone = "Silverpine Forest", level = "13–14", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sri'skulk", zone = "Tirisfal Glades", level = "13", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Krethis Shadowspinner", zone = "Silverpine Forest", level = "15", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Tarantula", zone = "Redridge Mountains", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Deepmoss Creeper", zone = "Stonetalon Mountains", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Deepmoss Venomspitter", zone = "Stonetalon Mountains", level = "17–18", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Wood Lurker", zone = "Loch Modan", level = "17–18", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Pygmy Venom Web Spider", zone = "Duskwood", level = "18–19", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Deepmoss Webspinner", zone = "Stonetalon Mountains", level = "19–20", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Greater Tarantula", zone = "Redridge Mountains", level = "19–20", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Shanda the Spinner", zone = "Loch Modan", level = "19", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 3" } },
        { name = "Venom Web Spider", zone = "Duskwood", level = "19–20", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Forest Moss Creeper", zone = "Hillsbrad Foothills", level = "20–21", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Wildthorn Stalker", zone = "Ashenvale", level = "20–21", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Besseleth", zone = "Stonetalon Mountains", level = "21", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Cave Stalker", zone = "Wetlands", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Green Recluse", zone = "Duskwood", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 3" } },
        { name = "Leech Stalker", zone = "Wetlands", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Chatter", zone = "Redridge Mountains", level = "23", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 3" } },
        { name = "Black Widow Hatchling", zone = "Duskwood", level = "24–25", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Creepthess", zone = "Hillsbrad Foothills", level = "24", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 3" } },
        { name = "Giant Moss Creeper", zone = "Hillsbrad Foothills, Alterac Mountains", level = "24–25", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4" } },
        { name = "Leech Widow", zone = "Wetlands", level = "24", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 4" } },
        { name = "Wildthorn Venomspitter", zone = "Ashenvale", level = "24–25", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Carrion Recluse", zone = "Duskwood", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Moss Creeper", zone = "Hillsbrad Foothills", level = "26–27", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4" } },
        { name = "Naraxis", zone = "Duskwood", level = "27", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 4" } },
        { name = "Wildthorn Lurker", zone = "Ashenvale", level = "28–29", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4" } },
        { name = "Plains Creeper", zone = "Arathi Highlands", level = "32–33", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5" } },
        { name = "Darkmist Spider", zone = "Dustwallow Marsh, The Barrens", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Giant Plains Creeper", zone = "Arathi Highlands", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5" } },
        { name = "Darkmist Recluse", zone = "The Barrens, Dustwallow Marsh", level = "36–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sorrow Spinner", zone = "Swamp of Sorrows", level = "36–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Darkfang Venomspitter", zone = "Dustwallow Marsh", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Darkfang Creeper", zone = "Dustwallow Marsh", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5" } },
        { name = "Darkmist Silkspinner", zone = "Dustwallow Marsh, The Barrens", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Darkmist Widow", zone = "The Barrens", level = "40", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Deathstrike Tarantula", zone = "Swamp of Sorrows", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Giant Darkfang Spider", zone = "Dustwallow Marsh", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Glassweb Spider", zone = "Searing Gorge", level = "43–45", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Witherbark Broodguard", zone = "The Hinterlands", level = "44–45", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Searing Lava Spider", zone = "Searing Gorge", level = "45–47", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Greater Lava Spider", zone = "Searing Gorge", level = "47–49", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Timberweb Recluse", zone = "Azshara", level = "47–48", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Rekk'tilac", zone = "Searing Gorge", level = "48", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 7" } },
        { name = "Venom Mist Lurker", zone = "Western Plaguelands", level = "50–51", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sand Skitterer", zone = "Silithus", level = "55–56", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Gretheer", zone = "Silithus", level = "57", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Rock Stalker", zone = "Silithus", level = "57–58", speed = "2.0", rare = false, isNew = false, abilities = {  } }
    },
    ["Scorpid"] = {
        { name = "Scorpid Worker", zone = "Durotar", level = "3", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 1" } },
        { name = "Sarkoth", zone = "Durotar", level = "4", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 1" } },
        { name = "Clattering Scorpid", zone = "Durotar", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Armored Scorpid", zone = "Durotar", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Venomtail Scorpid", zone = "Durotar", level = "9–10", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2", "Scorpid Poison 1" } },
        { name = "Corrupted Scorpid", zone = "Durotar", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 1" } },
        { name = "Death Flayer", zone = "Durotar", level = "11", speed = "1.6", rare = true, isNew = false, abilities = { "Claw 2", "Scorpid Poison 1" } },
        { name = "Silithid Creeper", zone = "The Barrens", level = "20–21", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 1" } },
        { name = "Silithid Swarmer", zone = "The Barrens", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 1" } },
        { name = "Scorpashi Snapper", zone = "Desolace", level = "30–31", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 4", "Scorpid Poison 2" } },
        { name = "Scorpid Reaver", zone = "Thousand Needles", level = "31–32", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 4", "Scorpid Poison 2" } },
        { name = "Scorpid Terror", zone = "Thousand Needles", level = "33–34", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 2" } },
        { name = "Scorpashi Lasher", zone = "Desolace", level = "34–35", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 5", "Scorpid Poison 2" } },
        { name = "Vile Sting", zone = "Thousand Needles", level = "35", speed = "2.0", rare = true, isNew = false, abilities = { "Claw 5", "Scorpid Poison 2" } },
        { name = "Scorpashi Venomlash", zone = "Desolace", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 2" } },
        { name = "Scorpid Hunter", zone = "Tanaris", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 6", "Scorpid Poison 3" } },
        { name = "Scorpid Tail Lasher", zone = "Tanaris", level = "43–44", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 3" } },
        { name = "Scorpid Dunestalker", zone = "Tanaris", level = "46–47", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 3" } },
        { name = "Venomtip Scorpid", zone = "Burning Steppes", level = "52–53", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 3" } },
        { name = "Deathlash Scorpid", zone = "Burning Steppes", level = "54–55", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 7", "Scorpid Poison 3" } },
        { name = "Stonelash Scorpid", zone = "Silithus", level = "54–55", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 3" } },
        { name = "Firetail Scorpid", zone = "Burning Steppes", level = "56–57", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 4" } },
        { name = "Krellack", zone = "Silithus", level = "56", speed = "2.0", rare = true, isNew = false, abilities = { "Scorpid Poison 4" } },
        { name = "Stonelash Pincer", zone = "Silithus", level = "56", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 4" } },
        { name = "Stonelash Flayer", zone = "Silithus", level = "57–58", speed = "2.0", rare = false, isNew = false, abilities = { "Scorpid Poison 4" } }
    },
    ["Crab"] = {
        { name = "Pygmy Surf Crawler", zone = "Durotar", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 1" } },
        { name = "Surf Crawler", zone = "Durotar", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Encrusted Surf Crawler", zone = "Durotar", level = "9–10", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Pygmy Tide Crawler", zone = "Darkshore", level = "9–10", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Corrupted Surf Crawler", zone = "Durotar", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Reef Crawler", zone = "Darkshore", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Tide Crawler", zone = "Darkshore", level = "12–14", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Sand Crawler", zone = "Westfall", level = "13–14", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Reef Crawler", zone = "Darkshore", level = "15–17", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sea Crawler", zone = "Westfall", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Shore Crawler", zone = "Westfall", level = "17–18", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Encrusted Tide Crawler", zone = "Darkshore", level = "18–20", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Silithid Protector", zone = "The Barrens", level = "18–19", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Clattering Crawler", zone = "Ashenvale", level = "19–20", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Raging Reef Crawler", zone = "Darkshore", level = "20–21", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Spined Crawler", zone = "Ashenvale", level = "20–21", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Enraged Reef Crawler", zone = "Desolace", level = "30–32", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Silt Crawler", zone = "Swamp of Sorrows", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 6" } },
        { name = "Southern Sand Crawler", zone = "Stranglethorn Vale", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Monstrous Crawler", zone = "Swamp of Sorrows", level = "43–44", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 6" } }
    },
    ["Bird of Prey"] = {
        { name = "Strigid Owl", zone = "Teldrassil", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 1" } },
        { name = "Strigid Screecher", zone = "Teldrassil", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Strigid Hunter", zone = "Teldrassil", level = "8–9", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Jai'vhanel", zone = "Darkshore", level = "12", speed = "2.0", rare = false, isNew = true, abilities = {  } },
        { name = "Ironbeak Owl", zone = "Felwood", level = "48–49", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 2" } },
        { name = "Ironbeak Hunter", zone = "Felwood", level = "50–51", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 7", "Dive 3" } },
        { name = "Ironbeak Screecher", zone = "Felwood", level = "52–53", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 3" } },
        { name = "Olm the Wise", zone = "Felwood", level = "52", speed = "2.0", rare = true, isNew = false, abilities = { "Claw 7", "Dive 3" } },
        { name = "Winterspring Owl", zone = "Winterspring", level = "54–56", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 7", "Dive 3" } },
        { name = "Winterspring Screecher", zone = "Winterspring", level = "57–59", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 8", "Dive 3" } }
    },
    ["Carrion Bird"] = {
        { name = "Wiry Swoop", zone = "Mulgore", level = "5–7", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Swoop", zone = "Mulgore", level = "7–9", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Taloned Swoop", zone = "Mulgore", level = "8–10", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Fleshripper", zone = "Westfall", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Fleshripper", zone = "Westfall", level = "13–14", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Lord Condar", zone = "Loch Modan", level = "15–16", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Mountain Buzzard", zone = "Loch Modan", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Greater Fleshripper", zone = "Westfall", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Dire Condor", zone = "Redridge Mountains", level = "18–19", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Vultros", zone = "Westfall", level = "26", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Salt Flats Scavenger", zone = "Thousand Needles", level = "30–32", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Mesa Buzzard", zone = "Arathi Highlands", level = "31–32", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 1" } },
        { name = "Dread Swoop", zone = "Desolace", level = "32–33", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Salt Flats Vulture", zone = "Thousand Needles", level = "32–34", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mesa Buzzard", zone = "Arathi Highlands", level = "34–35", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 1" } },
        { name = "Carrion Horror", zone = "Desolace", level = "35–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Starving Buzzard", zone = "Badlands", level = "35–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Dread Flyer", zone = "Desolace", level = "36–37", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 1" } },
        { name = "Buzzard", zone = "Badlands", level = "37–39", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Mesa Buzzard", zone = "Arathi Highlands", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Dread Ripper", zone = "Desolace", level = "39–40", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Giant Buzzard", zone = "Badlands", level = "39–41", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Roc", zone = "Tanaris", level = "41–43", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 2" } },
        { name = "Fire Roc", zone = "Tanaris", level = "43–45", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 2" } },
        { name = "Greater Firebird", zone = "Tanaris", level = "46", speed = "2.0", rare = true, isNew = false, abilities = { "Dive 2" } },
        { name = "Searing Roc", zone = "Tanaris", level = "47–49", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 2" } },
        { name = "Carrion Vulture", zone = "Western Plaguelands", level = "50–52", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 3" } },
        { name = "Zaricotl", zone = "Badlands", level = "55", speed = "2.0", rare = true, isNew = false, abilities = { "Dive 3" } }
    },
    ["Bear"] = {
        { name = "Young Black Bear", zone = "Dun Morogh", level = "5–6", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Black Bear", zone = "Dun Morogh", level = "6–7", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 1" } },
        { name = "Ice Claw Bear", zone = "Dun Morogh", level = "7–8", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 1" } },
        { name = "Young Forest Bear", zone = "Elwynn Forest", level = "8–9", speed = "2.5", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Thistle Cub", zone = "Darkshore", level = "9–10", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Black Bear", zone = "Loch Modan", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ferocious Grizzled Bear", zone = "Silverpine Forest", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Mangeclaw", zone = "Dun Morogh", level = "11", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Thistle Bear", zone = "Darkshore", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 2" } },
        { name = "Bjarn", zone = "Dun Morogh", level = "12", speed = "2.0", rare = true, isNew = false, abilities = { "Claw 2" } },
        { name = "Giant Grizzled Bear", zone = "Silverpine Forest", level = "12–13", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Grizzled Black Bear", zone = "Loch Modan", level = "13–14", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Old Vicejaw", zone = "Silverpine Forest", level = "14", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Black Bear Patriarch", zone = "Loch Modan", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Grizzled Thistle Bear", zone = "Darkshore", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Den Mother", zone = "Darkshore", level = "18–19", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Ol' Sooty", zone = "Loch Modan", level = "20", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Ashenvale Bear", zone = "Ashenvale, The Barrens", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Gray Bear", zone = "Hillsbrad Foothills, Alterac Mountains", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 3" } },
        { name = "Vicious Gray Bear", zone = "Hillsbrad Foothills", level = "22–23", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Ashenvale Bear", zone = "Ashenvale", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 4" } },
        { name = "Elder Gray Bear", zone = "Hillsbrad Foothills, Alterac Mountains", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Big Samras", zone = "Hillsbrad Foothills", level = "27", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Giant Ashenvale Bear", zone = "Ashenvale", level = "29–30", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ursol'lok", zone = "Ashenvale", level = "31", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Ironfur Bear", zone = "Feralas", level = "41–42", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 6" } },
        { name = "Old Grizzlegut", zone = "Feralas", level = "43", speed = "2.0", rare = true, isNew = false, abilities = { "Claw 6" } },
        { name = "Grizzled Ironfur Bear", zone = "Feralas", level = "44–45", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Angerclaw Bear", zone = "Felwood", level = "47–48", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ironfur Patriarch", zone = "Feralas", level = "48–49", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 7" } },
        { name = "Angerclaw Mauler", zone = "Felwood", level = "49–50", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 7" } },
        { name = "Mongress", zone = "Felwood", level = "50", speed = "2.0", rare = true, isNew = false, abilities = { "Claw 7" } },
        { name = "Angerclaw Grizzly", zone = "Felwood", level = "51–52", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Diseased Black Bear", zone = "Western Plaguelands", level = "51–52", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Shardtooth Bear", zone = "Winterspring", level = "53–54", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 7" } },
        { name = "Shardtooth Mauler", zone = "Winterspring", level = "55–56", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ursius", zone = "Winterspring", level = "56", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Shardtooth", zone = "Winterspring", level = "57–58", speed = "2.0", rare = false, isNew = false, abilities = { "Claw 8" } },
        { name = "Rabid Shardtooth", zone = "Winterspring", level = "59–60", speed = "2.0", rare = false, isNew = false, abilities = {  } }
    },
    ["Raptor"] = {
        { name = "Bloodtalon Taillasher", zone = "Durotar", level = "6–8", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Bloodtalon Scythemaw", zone = "Durotar", level = "8–10", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Corrupted Bloodtalon Scythemaw", zone = "Durotar", level = "10–11", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sunscale Lashtail", zone = "The Barrens", level = "11–13", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sunscale Screecher", zone = "The Barrens", level = "13–15", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Deviate Creeper", zone = "The Barrens", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Deviate Stalker", zone = "The Barrens", level = "15–17", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Deviate Slayer", zone = "The Barrens", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sunscale Scytheclaw", zone = "The Barrens", level = "16–18", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Takk the Leaper", zone = "The Barrens", level = "19", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Mottled Raptor", zone = "Wetlands", level = "22–23", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Highland Raptor", zone = "Wetlands", level = "23–24", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Highland Lashtail", zone = "Wetlands", level = "24–25", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mottled Screecher", zone = "Wetlands", level = "24–25", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Highland Scytheclaw", zone = "Wetlands", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mottled Scytheclaw", zone = "Wetlands", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mottled Razormaw", zone = "Wetlands", level = "26–27", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Highland Razormaw", zone = "Wetlands", level = "27–28", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Razormaw", zone = "Wetlands", level = "29", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sarltooth", zone = "Wetlands", level = "29", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Highland Strider", zone = "Arathi Highlands", level = "30–31", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Stranglethorn Raptor", zone = "Stranglethorn Vale", level = "30–31", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Razormaw Matriarch", zone = "Wetlands", level = "31", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Highland Thrasher", zone = "Arathi Highlands", level = "33–34", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Stranglethorn Raptor", zone = "Stranglethorn Vale", level = "33–34", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Lashtail Raptor", zone = "Stranglethorn Vale", level = "33–34", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Bloodfen Raptor", zone = "Dustwallow Marsh", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Lashtail Raptor", zone = "Stranglethorn Vale", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Bloodfen Screecher", zone = "Dustwallow Marsh", level = "36–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Highland Fleshstalker", zone = "Arathi Highlands", level = "36–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Jungle Stalker", zone = "Stranglethorn Vale", level = "36–37", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Dart", zone = "Dustwallow Marsh", level = "38", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Bloodfen Razormaw", zone = "Dustwallow Marsh", level = "39–40", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Bloodfen Lashtail", zone = "Dustwallow Marsh", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Jungle Stalker", zone = "Stranglethorn Vale", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Tethis", zone = "Stranglethorn Vale", level = "43", speed = "2.0", rare = false, isNew = false, abilities = {  } }
    },
    ["Crocolisk"] = {
        { name = "Dreadmaw Crocolisk", zone = "Durotar, The Barrens", level = "9–11", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 1" } },
        { name = "Corrupted Dreadmaw Crocolisk", zone = "Durotar, The Barrens", level = "11–12", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Loch Crocolisk", zone = "Loch Modan", level = "14–15", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Young Wetlands Crocolisk", zone = "Wetlands", level = "21–22", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Large Loch Crocolisk", zone = "Loch Modan", level = "22", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 3" } },
        { name = "Wetlands Crocolisk", zone = "Wetlands", level = "23–24", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Giant Wetlands Crocolisk", zone = "Wetlands", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4" } },
        { name = "River Crocolisk", zone = "Stranglethorn Vale", level = "30–31", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Drywallow Crocolisk", zone = "Dustwallow Marsh", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5" } },
        { name = "Saltwater Crocolisk", zone = "Stranglethorn Vale", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Snapjaw Crocolisk", zone = "Stranglethorn Vale", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Young Sawtooth Crocolisk", zone = "Swamp of Sorrows", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Drywallow Snapper", zone = "Dustwallow Marsh", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Elder Saltwater Crocolisk", zone = "Stranglethorn Vale", level = "38", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Mottled Drywallow Crocolisk", zone = "Dustwallow Marsh", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5" } },
        { name = "Sawtooth Crocolisk", zone = "Swamp of Sorrows", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ripscale", zone = "Dustwallow Marsh", level = "39", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 6" } },
        { name = "Drywallow Daggermaw", zone = "Dustwallow Marsh", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Sawtooth Snapper", zone = "Swamp of Sorrows", level = "41–42", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Deadmire", zone = "Dustwallow Marsh", level = "45", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 6" } },
        { name = "Sewer Beast", zone = "Stormwind City", level = "50", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 7" } }
    },
    ["Hyena"] = {
        { name = "Kolkar Packhound", zone = "The Barrens", level = "13", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Hecklefang Hyena", zone = "The Barrens", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Snort the Heckler", zone = "The Barrens", level = "17", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Hecklefang Snarler", zone = "The Barrens", level = "18–19", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Hecklefang Stalker", zone = "The Barrens", level = "22–23", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Galak Packhound", zone = "Thousand Needles", level = "24", speed = "1.5", rare = false, isNew = false, abilities = {  } },
        { name = "Pesterhide Hyena", zone = "Thousand Needles", level = "26–27", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Pesterhide Snarler", zone = "Thousand Needles", level = "28–29", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Starving Bonepaw", zone = "Desolace", level = "30–32", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Bonepaw Hyena", zone = "Desolace", level = "33–35", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Giggler", zone = "Desolace", level = "34", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Rabid Bonepaw", zone = "Desolace", level = "36–38", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Magram Bonepaw", zone = "Desolace", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 1" } },
        { name = "Starving Blisterpaw", zone = "Tanaris", level = "41–42", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 2" } },
        { name = "Murderous Blisterpaw", zone = "Tanaris", level = "43", speed = "2.0", rare = true, isNew = false, abilities = { "Dash 2" } },
        { name = "Blisterpaw Hyena", zone = "Tanaris", level = "44–45", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 2" } },
        { name = "Rabid Blisterpaw", zone = "Tanaris", level = "47–48", speed = "2.0", rare = false, isNew = false, abilities = { "Dash 2" } },
        { name = "Snickerfang Hyena", zone = "Blasted Lands", level = "49–50", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ravage", zone = "Blasted Lands", level = "51", speed = "1.3", rare = true, isNew = false, abilities = { "Dash 3" } }
    },
    ["Wind Serpent"] = {
        { name = "Deviate Coiler", zone = "The Barrens", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 2" } },
        { name = "Deviate Stinglash", zone = "The Barrens", level = "16–17", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 2" } },
        { name = "Thunderhawk Hatchling", zone = "The Barrens", level = "18–20", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 2" } },
        { name = "Thunderhawk Cloudscraper", zone = "The Barrens", level = "20–22", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 2" } },
        { name = "Greater Thunderhawk", zone = "The Barrens", level = "23–24", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 2" } },
        { name = "Azzere the Skyblade", zone = "The Barrens", level = "25", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Cloud Serpent", zone = "Thousand Needles", level = "25–26", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 3" } },
        { name = "Washte Pawne", zone = "The Barrens", level = "25", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 3" } },
        { name = "Venomous Cloud Serpent", zone = "Thousand Needles", level = "26–28", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 3" } },
        { name = "Elder Cloud Serpent", zone = "Thousand Needles", level = "27–29", speed = "2.0", rare = false, isNew = false, abilities = { "Lightning Breath 3" } },
        { name = "Noxious Flayer", zone = "Dustwallow Marsh", level = "35–36", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 1" } },
        { name = "Noxious Reaver", zone = "Dustwallow Marsh", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 1", "Lightning Breath 4" } },
        { name = "Noxious Shredder", zone = "Dustwallow Marsh", level = "38–39", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 1", "Lightning Breath 4" } },
        { name = "Hayoc", zone = "Dustwallow Marsh", level = "41", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Vale Screecher", zone = "Feralas", level = "41–43", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 2", "Lightning Breath 4" } },
        { name = "Rogue Vale Screecher", zone = "Feralas", level = "44–46", speed = "2.0", rare = false, isNew = false, abilities = { "Dive 2", "Lightning Breath 4" } },
        { name = "Arash-ethis", zone = "Feralas", level = "49", speed = "2.0", rare = true, isNew = false, abilities = { "Dive 2", "Lightning Breath 5" } }
    },
    ["Turtle"] = {
        { name = "Oasis Snapjaw", zone = "The Barrens", level = "15–16", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 2" } },
        { name = "Snapjaw", zone = "Alterac Mountains, Hillsbrad Foothills", level = "30–31", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 4", "Shell Shield 1" } },
        { name = "Sparkleshell Tortoise", zone = "Thousand Needles", level = "30–31", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Cranky Benj", zone = "Alterac Mountains", level = "32", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 4", "Shell Shield 1" } },
        { name = "Sparkleshell Borer", zone = "Thousand Needles", level = "32–33", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Sparkleshell Snapper", zone = "Thousand Needles", level = "34–35", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 5" } },
        { name = "Mudrock Spikeshell", zone = "Dustwallow Marsh", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Steeljaw Snapper", zone = "Tanaris", level = "42–43", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Giant Surf Glider", zone = "Tanaris", level = "48–50", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 7", "Shell Shield 1" } },
        { name = "Surf Glider", zone = "Tanaris", level = "48–50", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Saltwater Snapjaw", zone = "The Hinterlands", level = "49–50", speed = "2.0", rare = false, isNew = false, abilities = { "Bite 7" } },
        { name = "Coralshell Tortoise", zone = "Azshara", level = "50–52", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Ironback", zone = "The Hinterlands", level = "51", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 7", "Shell Shield 1" } },
        { name = "Coralshell Lurker", zone = "Azshara", level = "53–54", speed = "2.0", rare = false, isNew = false, abilities = {  } }
    },
    ["Gorilla"] = {
        { name = "Mistvale Gorilla", zone = "Stranglethorn Vale", level = "32–33", speed = "2.0", rare = false, isNew = false, abilities = { "Thunderstomp 1" } },
        { name = "Jungle Thunderer", zone = "Stranglethorn Vale", level = "37–38", speed = "2.0", rare = false, isNew = false, abilities = { "Thunderstomp 1" } },
        { name = "Elder Mistvale Gorilla", zone = "Stranglethorn Vale", level = "40–41", speed = "2.0", rare = false, isNew = false, abilities = { "Thunderstomp 2" } },
        { name = "Groddoc Ape", zone = "Feralas", level = "42–43", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Kurmokk", zone = "Stranglethorn Vale", level = "42", speed = "2.0", rare = true, isNew = false, abilities = {  } },
        { name = "Silverback Patriarch", zone = "Stranglethorn Vale", level = "42–43", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Groddoc Thunderer", zone = "Feralas", level = "49–50", speed = "2.0", rare = false, isNew = false, abilities = { "Thunderstomp 2" } },
        { name = "Skymane Gorilla", zone = "Stranglethorn Vale", level = "50", speed = "2.0", rare = false, isNew = false, abilities = {  } },
        { name = "Uhk'loc", zone = "Un'Goro Crater", level = "52–53", speed = "2.0", rare = true, isNew = false, abilities = { "Bite 7" } },
        { name = "U'cha", zone = "Un'Goro Crater", level = "55", speed = "2.0", rare = false, isNew = false, abilities = { "Thunderstomp 3" } }
    },
}
